// Generates src/version.ts from package.json so CARD_VERSION
// has a single source of truth. Runs as `prebuild`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(here, '..', 'package.json'), 'utf8'));
const target = resolve(here, '..', 'src', 'version.ts');

const banner = '// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n';
writeFileSync(target, `${banner}export const CARD_VERSION = '${pkg.version}';\n`);

// eslint-disable-next-line no-console
console.log(`gen-version: wrote src/version.ts (${pkg.version})`);
