// Generates src/fonts.ts containing @font-face CSS with base64-encoded woff2
// data URIs for Manrope (400/600/700) and Inter (400/500/600). These weights
// match what shared.ts and tokens.ts actually use.
//
// Self-hosting the fonts:
//   • removes the runtime fetch to fonts.googleapis.com on every dashboard load
//   • eliminates FOUT (flash of unstyled text) after a cache miss
//   • works on air-gapped HA instances
//
// The trade-off is ~120 KB added to the bundle (gzipped ~80 KB) — cached once
// in the browser per release, then free. Material Symbols was previously
// CDN-loaded too; verified unused (every icon in src/ is mdi:* served by
// HA's native <ha-icon>), so it's dropped entirely.
//
// Runs as `prebuild`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const FONTS = [
  { family: 'Manrope', pkg: '@fontsource/manrope', weight: 400 },
  { family: 'Manrope', pkg: '@fontsource/manrope', weight: 600 },
  { family: 'Manrope', pkg: '@fontsource/manrope', weight: 700 },
  { family: 'Inter',   pkg: '@fontsource/inter',   weight: 400 },
  { family: 'Inter',   pkg: '@fontsource/inter',   weight: 500 },
  { family: 'Inter',   pkg: '@fontsource/inter',   weight: 600 },
];

function loadWoff2({ pkg, family, weight }) {
  const slug = family.toLowerCase();
  const path = resolve(root, 'node_modules', pkg, 'files', `${slug}-latin-${weight}-normal.woff2`);
  return readFileSync(path);
}

function fontFaceCss({ family, weight, bytes }) {
  const b64 = bytes.toString('base64');
  return `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('data:font/woff2;base64,${b64}') format('woff2');
}`;
}

let totalBytes = 0;
const blocks = FONTS.map((f) => {
  const bytes = loadWoff2(f);
  totalBytes += bytes.length;
  return fontFaceCss({ ...f, bytes });
});

const css = blocks.join('\n\n');

const banner = '// AUTO-GENERATED by scripts/inline-fonts.mjs — do not edit by hand.\n';
const body = `${banner}export const FONT_FACES_CSS = ${JSON.stringify(css)};\n`;

writeFileSync(resolve(root, 'src', 'fonts.ts'), body);

// eslint-disable-next-line no-console
console.log(`inline-fonts: wrote src/fonts.ts (${FONTS.length} weights, ${(totalBytes / 1024).toFixed(1)} KB raw)`);
